# Local Docker Compose Configuration
version: '3.8'

services:
  makao-shop-db:
    image: postgres:latest
    container_name: makao-shop-postgres
    environment:
      POSTGRES_USER: makao
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: makao_shop_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "makao", "-d", "makao_shop_db" ]
      interval: 10s
      retries: 5
      start_period: 10s

  makao-shop-api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: makao-shop-api
    restart: unless-stopped
    depends_on:
      makao-shop-db:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  postgres-data: