spring:
  datasource:
    url: jdbc:postgresql://makao-shop-db:5432/makao_shop_db
    username: makao
    password: test1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql