spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/makao-shop-db
    username: makao
    password: test1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql