auth:
  access-token:
    secret: tesaevdv123edsftesaevdv123edsftesaevdv123
    expiration: 1000 * 60 * 5 # 5 minutes
  refresh-token:
    secret: tesaevdv123edsftesaevdv123edsftesaevdv112
    expiration: 1000 * 60 * 60 * 3 # 3 hours
  is-dev-env: true