spring:
  application:
    name: makao-shop

  profiles:
    include: local-db
    active: prod-db

  jpa:
    show-sql: true
    properties:
      hibernate:
        highlight_sql: true
        globally_quoted_identifiers: true

logging:
  level:
    root: INFO
    kr.co.shop.makao: DEBUG